import { sql } from "drizzle-orm";
import { index, jsonb, pgTable, text, timestamp, uuid } from "drizzle-orm/pg-core";

/*
  The document shape stored in `content`.

  It is deliberately permissive: this file must not become a second copy of the
  editor's ProseMirror schema. The editor owns which node and mark types are
  valid; this type only describes the envelope TipTap emits (`editor.getJSON()`),
  so the column round-trips a document unchanged. A future change to the
  editor's extension list is a change to *data*, not to this type, and is
  handled by a content migration rather than by a type error here.
*/
export type TiptapDoc = {
  type: string;
  content?: unknown[];
  [key: string]: unknown;
};

/*
  The empty document the editor starts with. Matches the schema TipTap accepts
  in `app/page.tsx`, and is the column default so a document can never be
  inserted without content.
*/
export const EMPTY_TIPTAP_DOC: TiptapDoc = {
  type: "doc",
  content: [{ type: "paragraph" }],
};

export const documents = pgTable(
  "documents",
  {
    /*
      The id is generated by PostgreSQL, not by the application, so the same
      migration produces identical ids in every environment and no client can
      choose one.

      `gen_random_uuid()` is built in from PostgreSQL 13, which is every Neon
      plan. It produces a v4 UUID. If the Neon project is moved to PostgreSQL
      18, swapping this to `uuidv7()` makes the id time-ordered (better index
      locality, sortable by creation) without changing anything else.
    */
    id: uuid("id")
      .primaryKey()
      .default(sql`gen_random_uuid()`),

    // Matches the frontend default at app/components/editorUi.tsx:13.
    title: text("title").notNull().default("Untitled document"),

    // TipTap JSON, not rendered HTML: the editor consumes it directly through
    // `editor.commands.setContent()`, so nothing is parsed or rebuilt on load.
    content: jsonb("content")
      .$type<TiptapDoc>()
      .notNull()
      .default(sql`'{"type":"doc","content":[{"type":"paragraph"}]}'::jsonb`),

    // timestamptz, not timestamp: UTC is unambiguous, which the recent
    // documents list depends on.
    createdAt: timestamp("created_at", { withTimezone: true, mode: "date" })
      .notNull()
      .defaultNow(),

    // `defaultNow()` only fires on INSERT, so the migration also installs a
    // `BEFORE UPDATE` trigger (`documents_set_updated_at`) that sets this to
    // `now()`. Drizzle's schema DSL cannot express a trigger, so it lives as
    // hand-written SQL at the end of the initial migration. Changing anything
    // here does not change the trigger; check that file too.
    updatedAt: timestamp("updated_at", { withTimezone: true, mode: "date" })
      .notNull()
      .defaultNow(),
  },
  // Serves "recent documents" (ORDER BY updated_at DESC), and later a
  // per-user list once ownership exists.
  (table) => [index("documents_updated_at_idx").on(table.updatedAt)],
);

export type DocumentRow = typeof documents.$inferSelect;
export type NewDocumentRow = typeof documents.$inferInsert;
