import { NextRequest, NextResponse } from "next/server";

import { db } from "@/db";
import { documents, EMPTY_TIPTAP_DOC, type TiptapDoc } from "@/drizzle/schema";

/**
 * Create a new document.
 *
 * POST /api/documents
 * Body: { title?: string, content?: TiptapDoc }
 *
 * The id is generated by PostgreSQL (`gen_random_uuid()`), so the client never
 * chooses one and the returned row is already addressable at `/[id]`.
 */
export async function POST(request: NextRequest) {
  let body: { title?: string; content?: TiptapDoc };

  try {
    body = await request.json();
  } catch {
    return NextResponse.json({ error: "Invalid JSON" }, { status: 400 });
  }

  const title = body.title?.trim() || "Untitled document";
  const content = body.content ?? EMPTY_TIPTAP_DOC;

  try {
    const [created] = await db
      .insert(documents)
      .values({ title, content })
      .returning();

    return NextResponse.json(created, { status: 201 });
  } catch {
    return NextResponse.json(
      { error: "Failed to create document" },
      { status: 500 },
    );
  }
}
